### ISSUE TITLE
"sync:methodName" "async:methodName" for object functionality doesn't work

### ISSUE THREAD

**Issue by donald-richardson-dxd** [snapwich/fun-hooks#34]
hook(obj, method, name) works (albeit with a typescript error) only when used without the async or sync prefix.

**Comment by donald-richardson-dxd** [comment]
Looks like it gets filtered out at the beginning of the `do` loop in `hookObj`.

**Comment by snapwich** [comment]
thanks for catching this. pushed a fix in v1.0.4. i also updated the typescript types so it shouldn't have an error anymore when hooking objects. although the return isn't that great since the object hooking API doesn't lend itself very well to good types; but you can pass in your own type parameter if you want better type safety than any.
